### PR TITLE
Implemented Server system

### PR DESCRIPTION
**Pull request by Orangefruit2**
-Commended out the GUI in the OrderController.
-Instead of the GUI,  I implemented as discussed the server system. I used the Observer/Listener pattern. I added a short draft class Diagramm ( documentation/DraftClassDiagramServerObersverPattern.dia), so 
 you can see the changes.

-Now the Programm starts and read all orders. 5 servers read the orders concurrently and print some output. As soon as all Orders are finished, the Programm stops. 

-I changed the type of the orderList inside the Ordercontoller class from a list to a queue. In the server, I always remove the first element from the queue. This is a cheap operation for a queue, but not for (most) lists. Furthermore, we do not need the capability to get a Order at index n. We only add orders at the tail, and remove orders at the head. In the GUI, we will only iterate over the whole list.

-I also added more orders in Orders.csv and and a toString() method in Order.java

### CODE REVIEW

**Comment by Orangefruit2** [comment]
This fixes Issue #101

**Comment by Orangefruit2** [comment]
1.OrderController is meant to be affected as part of this issue. To make thinks working I _have to_ change Order controller (Ok i could change the main method of this project, so i do not touch the OrderController class directly, but this would make it in the end more complicated (not complicated but more complicated) because in the end we have to change the OrderController anyway because we need a reference to a server-order handling system inside the OrderController class. So, we can do it now.  
Furhtermore, #102 is about the _new GUI_ which works with the new _server-order handling system_ (what i did). So, to fix #102 we need this changes in Ordercontroller.

2. We did not think of any design during our discussion. So I choose one, because this was my problem to solve, which is part of agile programming. If you have suggestions for a better design, tell me. But we don't have to discuss every small problem in the whole group, because this will only slow down the whole project. If you find improvements or big issues with the solution, tell me and I will change it.

3. Did this for first debugging purposes, to check if everything works as expect. I left this change in because it is only a minor change, which does not affect any other part of our program and does not change any logic but can help us to find errors.

4. Agree with you

**Comment by jathanasiou** [comment]
Points 3 & 4 are relatively minor so I don't think there's any disagreement there on my part.   

1+2 Are somewhat connected because of they massive changes to the `control` package territory.  

> To make thinks working I have to change Order controller

The program doesn't need to compile when we're drastically transitioning. Furthermore, while every developer has control over their solution/implementation it would be wise for us not to step on each other's toes and responsibilities.   

That being said, and considering how clear our responsibilities were made in the last meeting were made I would suggest this:  

a) Interfaces are a nice touch, they make sense in providing direction. Perhaps you could remove any changes from the OrderController however, so as to have it implement the OrderStatus interface at a later sprint, along with other other integration changes.  
b) Consider renaming OrderStatus -> OrderHandler to clarify it's purpose and future usage by a controller-style class.

**Comment by Orangefruit2** [comment]
The Programm always needs to compile on the master branch. Otherwise nobody can work, I think you mean compile able, but not running without errors?

I removed all changes in Orderclass (wish you fun, doing exactly the same changes later again :D)
Renamed OrderStatus to OrderHandler

**Pull request merged**
