### PR TITLE
Added Queue class

### PR DESCRIPTION
**Pull request by trz-maier**
There is a known issue whereby orders keep on being added all over again to the queue once you reach the end of it - I think this is caused by the while loop but I can't stop it unless I interrupt the thread. 

@Orangefruit2 could you review and make some suggestions?

### CODE REVIEW

**Comment by trz-maier** [comment]
#122

**Comment by trz-maier** [comment]
#122

**Comment by Orangefruit2** [comment]
Please use Desing patterns for the Queue class.
You can make an easy observer pattern:
-Create a Interface called OrderProducedListener with an function onOrderProduced(BlockingQueue<Order> order, Order producedOrdre).
-Add a field of type OrderProducedListener in the queue class.
-Add a parameter in the Queue class of type OrderProducedListener.
-And after a order is added in the Queue thread(Queue class line 27) you call orderProducedListener .onOrderProduced(queuedOrders,order)
This observer pattern will help us a lot, because it will give us a big flexibility. And you wont need the methods: addToQueue(Order order)   and Order takeFromQueue().
(currently we produce Orders, and some other class will ask your Queue class: "Hey do you have some orders? If not I will wait up to Infinity (And block the whole Thread)". With the Observer pattern your queue says:"Hey, here is a new fresh order, i will give the order the OrderProducedListener. I dont care what happens with the order, I only produce orders.")
The second approach is better, because 
   -nobody has to wait until a order is ready. The queue will notify if as soon as a order is ready. 
   -It is more flexible

In line 22 you do not need this:  while (!Thread.currentThread().isInterrupted())
Reason: After all orders are produced, the thread should close. Currently you will re-add all orders again to the queuedOrders queue.

In class  OrderController line 41: Queue queue = new Queue(this.readOrders);  queue.run();
You dont create a new Thread.
Do:
Thread t = new Thread(queue)
t.setName("Order producer");
t.start()
instead.
If you ask why: Read the learning material in Vision.



Small issues:
In line 12:  private List<Order> readOrders;
-> readorders can be also a Collection<Order> or Iterable<Order>, there is no reason why it has to be a list.
-> Please add the queuedOrders as parameter in the Constructor. So we can decide during runtime which implementation class of BlockingQueue we want to use

->If you add generics(https://docs.oracle.com/javase/tutorial/java/generics/types.html) int the Queue class, you can decide which kind of object should be produced (you could simply let the queue produce Items instead of orders during runtime, WE DO NOT NEED THIS, BUT THIS IS A COOL FEATURE :dancer: )

**Comment by Orangefruit2** [comment]
Also:
Queue is a unspecific name(Queues in Java are interfaces like List or Set)
So please rename the queue class(Since the whole ´thing is a Producer-Consumer pattern, you could call it OrderProducer or something like this)

**Pull request merged**
